### ISSUE TITLE
[Question] 机器人登录 QQ 后报错，与其他软件通讯不正常

### ISSUE THREAD

**Issue by RisingInIris2017** [yyuueexxiinngg/cqhttp-mirai#104]
### 系统环境
OS: Windows Server 2019 Datacenter
JRE: 
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.3.3) (build 1.8.0_242-b98)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.3.3) (build 25.242-b98, mixed mode)
```
### CQHTTP-Mirai 版本
cqhttp-mirai-0.2.3-embedded-all
### 问题描述
我有另一个程序，需要 Mirai 机器人向 5701 端口转发 QQ 消息。
但是我在机器人上登录了 QQ 号，之后启动了该程序之后，程序没有接收到机器人发来的任何信息。
[咨询了该程序的开发者](https://github.com/zhang-anzhi/CoolQAPI/issues/4) 后，确认不是程序问题，而是机器人的问题。
检查机器人的控制台日志后发现，机器人在连接 127.0.0.1:5701 时出现了问题，抛出了异常。
报错如下文所附带。
机器人配置文件很短，张贴如下：
```yaml
'<机器人QQ号>':
  http:
    enable: true
    host: 127.0.0.1
    port: 5700
    postUrl: "http://127.0.0.1:5701/post"
    postMessageFormat: array
```
### 报错
https://paste.ubuntu.com/p/nycyzT6qk7/
### 问题的补充说明
在出这个问题之前，我的机器人和其他程序的协作是正常的，可以相互正常通信。
但是我重启了一次服务器系统，再启动 Mirai 机器人及关联的程序，就出现了我上面提到的这个问题。
之后我又重启过一次系统，没能解决这一问题。
这个问题可能的解决途径有哪些？

如果还有其他没有提供的重要信息，我将尽量提供。
在此先感谢你的帮助！
